### ISSUE TITLE
When will the paper about this project be released?

### ISSUE THREAD

**Issue by diggerdu** [YannDubs/Invariant-Self-Supervised-Learning#1]
Many thanks for your insightful work. When will the paper about this project be released?

**Comment by YannDubs** [comment]
oops sorry, I didn't think anyone would see the repo before the paper. I will put it on arxiv at the end of the week!

**Comment by diggerdu** [comment]
> oops sorry, I didn't think anyone would see the repo before the paper. I will put it on arxiv at the end of the week!

Thanks for your reply!
